sonar.projectKey=python-ci-cd
sonar.projectName=Python CI/CD


sonar.projectBaseDir=.
sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**,**/__init__.py,**/__pycache__/**, **/main.py, **/logger.py,
sonar.python.coverage.forceZeroCoverage=false




